name: Build Images

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

  workflow_dispatch:  

jobs:
  build-images:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend, backend]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: hackathon-manager

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set image name and path
        id: vars
        run: |
          IMAGE_TAG=${{ github.ref_name }}
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/hackathon-${{ matrix.service }}
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Prepare build context
        run: |
          cd hackathon-manager/${{ matrix.service }}
          if [ "${{ matrix.service }}" == "frontend" ]; then
            npm install
            npm run build
          fi

      - name: Build and push image with tag
        run: |
          cd hackathon-manager/${{ matrix.service }}
          docker build \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            -t ${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.image_tag }} \
            -t ${{ steps.vars.outputs.image_name }}:latest \
            -f Dockerfile .
          docker push ${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.image_tag }}
          docker push ${{ steps.vars.outputs.image_name }}:latest
