name: Build Images

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

  workflow_dispatch:  # Manuelles Auslösen ermöglichen

jobs:
  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code Repository (hackathon-manager)
        uses: actions/checkout@v4
        with:
          repository: jenszech/hackathon-manager
          ref: 'develop'

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push frontend image
        run: |
          cd frontend
          npm install
          npm run build
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/hackathon-frontend:${{ github.ref_name }}
          docker build -t $IMAGE_NAME -f Dockerfile .
          docker push $IMAGE_NAME

  build-backend-image:
    runs-on: ubuntu-latest
    needs: build-frontend-image
    steps:
      - name: Checkout Source Code Repository (hackathon-manager)
        uses: actions/checkout@v4
        with:
          repository: jenszech/hackathon-manager
          path: /

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push backend image
        run: |
          cd backend
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/hackathon-backend:${{ github.ref_name }}
          docker build -t $IMAGE_NAME -f Dockerfile .
          docker push $IMAGE_NAME
