name: Manual Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            PROJECT_PATH="/opt/data/docker/containers/hackathon-manager"
            DOCKER_COMPOSE_FILE="$PROJECT_PATH/docker-compose.yaml"
            echo "Deploying to $PROJECT_PATH"
            mkdir -p $PROJECT_PATH
            cd $PROJECT_PATH

            echo "Stopping existing Docker stack"
            docker compose down --remove-orphans --timeout 30

            echo "Pulling latest Docker images"
            docker pull ghcr.io/${{ github.repository_owner }}/hackathon-frontend:${{ github.ref_name }}
            docker pull ghcr.io/${{ github.repository_owner }}/hackathon-backend:${{ github.ref_name }}

            echo "Updating docker-compose config if production"
            if [ "${{ github.ref_name }}" = "main" ]; then
              sed -i 's/hackathon-stg.drsbln.de/hackathon.drsbln.de/g' $DOCKER_COMPOSE_FILE
              sed -i 's/hackathon-stg.drsbln.de/hackathon.drsbln.de/g' /DOCKER/containers/hackathon-manager/frontend/nginx/default.conf
            fi

            echo "Restarting Docker stack"
            docker compose up -d --build
