name: Build, Push & Deploy Hackathon Manager

on:
  push:
    branches:
      - '**'
    paths:
      - 'frontend/**'
      - 'backend/**'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment (staging/production)'
        required: true
        default: 'staging'
      branch:
        description: 'Branch to deploy (default: main)'
        required: true
        default: 'develop'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  

    outputs:
      image_tag: ${{ steps.export.outputs.branch }}

    steps:
      - name: Sanitize branch name
        id: vars
        run: echo "branch=$(echo '${{ github.ref_name }}' | tr '/' '-' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/hackathon-frontend:${{ steps.vars.outputs.branch }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/hackathon-backend:${{ steps.vars.outputs.branch }}

      - name: Export branch as output
        id: export
        run: echo "branch=${{ steps.vars.outputs.branch }}" >> "$GITHUB_OUTPUT"
