name: Build, Push & Deploy Hackathon Manager

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment (staging/production)'
        required: true
        default: 'staging'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  

    outputs:
      image_tag: ${{ steps.export.outputs.image_tag }}

    steps:
      - name: Sanitize branch name
        id: vars
        run: echo "branch=$(echo '${{ github.ref_name }}' | tr '/' '-' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/hackathon-frontend:${{ steps.vars.outputs.branch }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/hackathon-backend:${{ steps.vars.outputs.branch }}

      - name: Export branch as output
        id: export
        run: echo "image_tag=${{ steps.vars.outputs.branch }}" >> "$GITHUB_OUTPUT"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: ${{ github.event.inputs.environment || 'staging' }}
      IMAGE_TAG: ${{ needs.build-and-push.outputs.image_tag }}

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.LOCAL_ANSIBLE_SSH_PRIVATE_KEY }}
          script: |
            export PROJECT_PATH="/opt/data/docker/containers/hackathon-manager"
            export DOCKER_COMPOSE_FILE="$PROJECT_PATH/docker-compose.yaml"

            echo "Deploying to environment: $DEPLOY_ENV"
            echo "Using image tag: $IMAGE_TAG"

            mkdir -p "$PROJECT_PATH"
            cd "$PROJECT_PATH"

            docker compose down --remove-orphans --timeout 30

            # Fix Git permissions (safe for CI/CD)
            sudo chown -R $USER:$USER "$PROJECT_PATH"
            git config --global --add safe.directory "$PROJECT_PATH"
            git pull --rebase=false origin main || echo "Git pull failed; please check manually!"

            # Auto-set correct image tags in docker-compose.yaml
            echo "Setting correct image tags in docker-compose.yaml"
            sed -i "s|ghcr.io/.*/hackathon-frontend:.*|ghcr.io/${GITHUB_REPOSITORY_OWNER}/hackathon-frontend:${IMAGE_TAG}|" "$DOCKER_COMPOSE_FILE"
            sed -i "s|ghcr.io/.*/hackathon-backend:.*|ghcr.io/${GITHUB_REPOSITORY_OWNER}/hackathon-backend:${IMAGE_TAG}|" "$DOCKER_COMPOSE_FILE"

            # Adjust for production environment if needed
            if [ "$DEPLOY_ENV" = "production" ]; then
              sed -i 's/hackathon-stg.drsbln.de/hackathon.drsbln.de/g' "$DOCKER_COMPOSE_FILE"
              sed -i 's/hackathon-stg.drsbln.de/hackathon.drsbln.de/g' /DOCKER/containers/hackathon-manager/frontend/nginx/default.conf
            fi

            # Pull and start containers with correct images
            docker compose pull
            docker compose up -d --build
